model:
  type: APBSN
  kwargs:
    pd : [4,2,1]
    dilation: 2
    width: 128
    
    enc_blk_nums: [3,4]
    middle_blk_nums: 4
    dec_blk_nums: [4,3]
    
    R3: True
    R3_T: 8
    R3_p: 0.16

    bsn: PUCA

    
model_input: [noisy] # e.g.) real_noisy, syn_noisy, clean

trainer: Trainer

training:
  dataset: prep_DND

  dataset_args:
    add_noise: None # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
    crop_size: [256,256]
    aug: ['hflip', 'rot']
    n_repeat: 4
  
  batch_size: 2

  max_epoch: 20
  
  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 8
      gamma: 0.1
  loss: 1*self_L1
  tmp_info: []
  optimizer:
    type: Adam
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 200

validation:
  dataset: prep_DND

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
    # n_data: 64

  add_con: 0.5
  floor: True

  val: True
  save_image: True
  
  start_epoch: 12
  interval_epoch: 4
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10

test:
  dataset: DND_benchmark

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.

  add_con: 0.0
  floor: False

  save_image: True
